setenv SHARC=/user/mai/SHARC/REPOSITORY/DEVELOPMENT/source/../bin
setenv PYSHARC=/user/mai/SHARC/REPOSITORY/DEVELOPMENT/source/../pysharc
setenv SHARCLIB=/user/mai/SHARC/REPOSITORY/DEVELOPMENT/source/../lib
setenv ANACONDA=/user/maximilian/anaconda2/
setenv PYTHONPATH=$SHARCLIB:$PYSHARC:$PYTHONPATH
setenv LD_LIBRARY_PATH=$SHARCLIB:$ANACONDA/lib:$LD_LIBRARY_PATH
