  integer, parameter :: u_dat=11          !< unit for output.dat file
  integer, parameter :: u_ener=21         !< energy.out
  integer, parameter :: u_dm=22           !< fosc.out
  integer, parameter :: u_spin=23         !< spin.out
  integer, parameter :: u_coefd=24        !< coeff_diag.out
  integer, parameter :: u_coefm=25        !< coeff_MCH.out
  integer, parameter :: u_prob=26         !< prob.out
  integer, parameter :: u_expec=27        !< expec.out
  integer, parameter :: u_coefdiab=28     !< coeff_diab.out
  integer, parameter :: u_expec_mch=29    !< expec_MCH.out
  integer, parameter :: u_fosc_act=30     !< fosc_act.out
  integer, parameter :: u_ref=31          !< Reference/QM.out
  integer, parameter :: u_info=42         !< output.dat.ext
  integer, parameter :: u_ion_diag=51     !< ion_diag.out
  integer, parameter :: u_ion_mch=52      !< ion_mch.out

  integer, parameter :: u_classd=61        !< JCP 139, 2111101 (2013), Method 1 (diag)
  integer, parameter :: u_classm=62        !< JCP 139, 2111101 (2013), Method 1 (MCH)
  integer, parameter :: u_classdiab=63     !< JCP 139, 2111101 (2013), Method 1 (diabatic)
  integer, parameter :: u_cmixd=64         !< JCP 139, 2111101 (2013), Method 3 (diag)
  integer, parameter :: u_cmixm=65         !< JCP 139, 2111101 (2013), Method 3 (MCH)
  integer, parameter :: u_cmixdiab=66      !< JCP 139, 2111101 (2013), Method 3 (diabatic)

  integer, parameter :: u_xyz=99        !< output.xyz